<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>CastDecoy</RootNamespace>
    <AssemblyName>CastDecoy</AssemblyName>
    <Nullable>enable</Nullable>
    <ApplicationIcon>Assets\icon.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DefaultItemExcludes>$(DefaultItemExcludes);installer\**</DefaultItemExcludes>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets\brand.png" />
    <Resource Include="Assets\icon.png" />
    <Resource Include="Assets\icon.ico" />
    <Resource Include="Assets\Kanit-Bold.ttf" />
    <None Update="ScreenSpoof\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FlashCap" Version="1.12.0" />
    <PackageReference Include="NAudio" Version="3.1.0" />
  </ItemGroup>
</Project>
